---
  - name: add the redis repository
    apt_repository:
      repo: "ppa:chris-lea/redis-server"
      state: present
      update_cache: yes

  - name: install apt packages
    apt: name={{item}} state=present
    with_items:
      - redis-server
