apps:
  - script: ./src/app.js
    name: iiif-server
    exec_mode: cluster
    instances: max
    env:
      NODE_ENV: production
      IIIF_SERVER_SERVICES: web,archivematica-index,iish-access,iish-auth-texts
      IIIF_SERVER_SECRET: secret
      IIIF_SERVER_ACCESS_TOKEN: secret
      IIIF_SERVER_UNIVERSAL_VIEWER_PATH: /opt/universalviewer/examples/uv
      IIIF_SERVER_ARCHIVAL_VIEWER_PATH: /opt/iiif-viewer/build
      IIIF_SERVER_UNIVERSAL_VIEWER_CONFIG_PATH: /opt/universalviewer-config.json
      IIIF_SERVER_IMAGE_SERVER_URL: http://image:8888
      IIIF_SERVER_IMAGE_TIER_SEPARATOR: _
      IIIF_SERVER_CACHE_DISABLED: false
      IIIF_SERVER_PORT: 3333
      IIIF_SERVER_LOGO: /data/additional/logo.png
      IIIF_SERVER_ATTRIBUTION: Provided by
      IIIF_SERVER_BASE_URL: http://127.0.0.1
      IIIF_SERVER_DATA_PATH: /data/collections
      IIIF_SERVER_LOG_LEVEL: debug
      IIIF_SERVER_INTERNAL_IP_ADDRESSES: 
      IIIF_SERVER_LOGIN_DISABLED: false
      IIIF_SERVER_ELASTICSEARCH_URL: http://elasticsearch:9200
      IIIF_SERVER_REDIS_DISABLED: false
      IIIF_SERVER_REDIS_HOST: redis
      IIIF_SERVER_REDIS_PORT: 6379
