---
  - name: install gpg key
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: add the nodejs repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: install apt packages
    apt: name={{item}} state=present
    with_items:
      - nodejs
      - build-essential
