---
- name: install apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: obtain the package
  git:
    repo: "{{ iiif_server_git }}"
    dest: "{{ iiif_server_path }}"
    force: "yes"
    version: iish

- name: install npm packages globally
  npm: name={{item}} global=yes
  with_items:
    - pm2

- name: install npm packages
  npm:
    production: "yes"
    path: "{{ iiif_server_path }}"

- name: set pm2 config
  template:
    src: config.yaml.j2
    dest: "{{ iiif_server_path }}/config.yaml"

- name: remove pm2 applications
  command: "pm2 delete all"

- name: undo old startup script
  command: "pm2 unstartup"

- name: setup startup script
  command: "pm2 startup --hp {{ iiif_server_path }}"

- name: start the application
  command: "pm2 start {{ iiif_server_path }}/config.yaml"

- name: save the application startup script
  command: "pm2 save"
