- name: Install module dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-9.5

- name: "Create user for CLI"
  user:
    name: "{{ db_user_name }}"
    home: "/home/{{ db_user_name }}"

- name: add role
  become_user: postgres
  postgresql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    role_attr_flags: "LOGIN,SUPERUSER"

- name: install the database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    owner: "{{ db_user_name }}"

- name: install the extensions
  become_user: postgres
  postgresql_lang:
    db: "{{ db_name }}"
    lang: "{{ item }}"
    state: present
  with_items:
    - plperlu

- name: add postgresql configuration
  template:
    dest: /etc/postgresql/9.5/main/postgresql.conf
    group: postgres
    owner: postgres
    src: postgresql.conf.j2
  notify: "restart postgresql"

- name: compile rules
  set_fact: hba_rules={{ system_hba_rules | combine(custom_hba_rules) }}

- name: add access rules
  template:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    group: postgres
    owner: postgres
    src: pg_hba_rule.conf.j2
  notify: "restart postgresql"
