# If imageServerUrl is missing the internal iiif image server will be used.
# Use loris, sipi  or another server for better performance
imageServerUrl: "http://localhost:8080/loris/"
port: 3333
defaultLang: de
logo: https://example.com/logo
database:
  user: database_user
  host: localhost
  database: database_name
  password: database_password
  port: 5432
